// Regenerates supabase/seed.sql from the bundled question banks.
// Run with: npx tsx scripts/generate-seed.ts
import { writeFileSync } from 'fs';
import { join } from 'path';
import { Question, RULESET_IDS } from '../src/types';
import { getBundledBank } from '../src/data/bundled';

const sqlString = (value: string) => `'${value.replace(/'/g, "''")}'`;

function rowSql(q: Question): string {
  return [
    sqlString(q.id),
    sqlString(q.ruleset),
    sqlString(q.topic),
    sqlString(q.tier),
    sqlString(q.scenario),
    `${sqlString(JSON.stringify(q.options))}::jsonb`,
    String(q.correctIndex),
    sqlString(q.explanation),
    "'published'",
  ].join(', ');
}

const questions = RULESET_IDS.flatMap((id) => getBundledBank(id));
const ids = new Set(questions.map((q) => q.id));
if (ids.size !== questions.length) {
  throw new Error('Duplicate question ids across banks; seed would clobber rows.');
}

const lines = [
  '-- Generated by scripts/generate-seed.ts — do not edit by hand.',
  '-- Seeds the bundled question banks as published rows. Safe to re-run:',
  '-- existing rows are updated in place and keep their ids, so SRS progress',
  '-- on devices is unaffected.',
  '',
  'insert into public.questions',
  '  (id, ruleset, topic, tier, scenario, options, correct_index, explanation, status)',
  'values',
  questions.map((q) => `  (${rowSql(q)})`).join(',\n'),
  'on conflict (id) do update set',
  '  ruleset = excluded.ruleset,',
  '  topic = excluded.topic,',
  '  tier = excluded.tier,',
  '  scenario = excluded.scenario,',
  '  options = excluded.options,',
  '  correct_index = excluded.correct_index,',
  '  explanation = excluded.explanation,',
  '  updated_at = now();',
  '',
];

const outPath = join(__dirname, '..', 'supabase', 'seed.sql');
writeFileSync(outPath, lines.join('\n'));
console.log(`Wrote ${questions.length} questions to ${outPath}`);
